In [1]:
from funlib.persistence import Array

import numpy as np

import zarr

In [2]:
container = zarr.open("example.zarr")
shape = (2, 3, 3)

ds = container.create_dataset(
    "raw",
    chunks=(1, 3, 3),
    dtype="f4",
    data=np.random.randn(*shape),
    overwrite=True,
)

In [3]:
array = Array(ds, (0, 0), (1, 1))
print(array[array.roi])

[[[-0.03777862  0.34548774 -0.67263967]
  [ 0.3058082   0.29156172 -0.9545453 ]
  [ 0.70072883 -1.5905756   0.06846493]]

 [[ 0.41885415  0.04308635 -0.457416  ]
  [-1.1773857  -0.15212785  1.2121304 ]
  [ 1.3966681  -0.16751394 -2.1650443 ]]]


In [5]:
array_sliced = Array(ds, (0, 0), (1, 1), adapter=(slice(1,2), 0, slice(None)))
print(array_sliced[array_sliced.roi])

[[ 0.41885415  0.04308635 -0.457416  ]]


In [6]:
array_sliced[array_sliced.roi] = array_sliced[array_sliced.roi] + 10
print(array_sliced[array_sliced.roi])

[[10.418854 10.043086  9.542584]]


In [7]:
array_sliced.adapt(np.s_[0])
array_sliced.adapt(np.s_[:2])
print(array_sliced[array_sliced.roi])
print(array_sliced.axis_names)

[10.418854 10.043086]
['d1']


In [8]:
thresholded = Array(ds, (0, 0), (1, 1), adapter=lambda x: x > 5)
print(thresholded.dtype)
print(thresholded[thresholded.roi])

bool
[[[False False False]
  [False False False]
  [False False False]]

 [[ True  True  True]
  [False False False]
  [False False False]]]


In [9]:

thresholded[thresholded.roi] = thresholded[thresholded.roi] + 10

RuntimeError: This array is not writeable since you have applied a custom callable adapter that may or may not be invertable.